In [1]:
import pandas as pd
import numpy as np

In [2]:
matches=pd.read_csv('matches.csv')
deliveries=pd.read_csv('deliveries.csv')

In [3]:
matches.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba

In [4]:
deliveries.head(120)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,18,4,BB McCullum,JH Kallis,Mohammad Hafeez,4,0,4,NaN,0,NaN,NaN,NaN
116,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,18,5,BB McCullum,JH Kallis,Mohammad Hafeez,1,0,1,NaN,0,NaN,NaN,NaN
117,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,18,6,Mohammad Hafeez,JH Kallis,BB McCullum,4,0,4,NaN,0,NaN,NaN,NaN
118,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,1,BB McCullum,P Kumar,Mohammad Hafeez,6,0,6,NaN,0,NaN,NaN,NaN
119,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,2,BB McCullum,P Kumar,Mohammad Hafeez,6,0,6,NaN,0,NaN,NaN,NaN

In [5]:
deliveries.shape

(260920, 17)

In [6]:
matches.shape

(1095, 20)

In [7]:
matches=matches[['id','city','team1','team2','winner','target_runs','method']]

In [8]:
matches['method'].unique()

array([nan, 'D/L'], dtype=object)

In [9]:
matches=matches[matches['method']!='D/L']

In [10]:
matches.head(20)

,id,city,team1,team2,winner,target_runs,method
0,335982,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,223.0,NaN
1,335983,Chandigarh,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,241.0,NaN
2,335984,Delhi,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,130.0,NaN
3,335985,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,166.0,NaN
4,335986,Kolkata,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,111.0,NaN
5,335987,Jaipur,Rajasthan Royals,Kings XI Punjab,Rajasthan Royals,167.0,NaN
6,335988,Hyderabad,Deccan Chargers,Delhi Daredevils,Delhi Daredevils,143.0,NaN
7,335989,Chennai,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,209.0,NaN
8,335990,Hyderabad,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,215.0,NaN
9,335991,Chandigarh,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,183.0,NaN
10,335992,Bangalore,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,136.0,NaN
11,335993,Chennai,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,148.0,NaN
12,335994,Mumbai,Mumbai Indians,Deccan Chargers,Deccan Chargers,155.0,NaN
13,335995,Chandigarh,Kings XI Punjab,Delhi Daredevils,Kings XI Punjab,159.0,NaN
14,335996,Bangalore,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,179.0,NaN
15,335997,Kolkata,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,138.0,NaN
16,335998,Delhi,Delhi Daredevils,Royal Challengers Bangalore,Delhi Daredevils,192.0,NaN
17,335999,Hyderabad,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,165.0,NaN
18,336000,Jaipur,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,197.0,NaN
19,336001,Chennai,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,170.0,NaN

In [11]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [12]:
teams=['Royal Challengers Bengaluru','Punjab Kings','Delhi Capitals','Mumbai Indians','Kolkata Knight Riders','Rajasthan Royals','Sunrisers Hyderabad','Lucknow Super Giants', 'Gujarat Titans','Chennai Super Kings']

In [13]:
matches['team1']=matches['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
matches['team2']=matches['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

matches['team1']=matches['team1'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')
matches['team2']=matches['team2'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')

matches['team1']=matches['team1'].str.replace('Kings XI Punjab','Punjab Kings')
matches['team2']=matches['team2'].str.replace('Kings XI Punjab','Punjab Kings')

matches['team1']=matches['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
matches['team2']=matches['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [14]:
matches=matches[matches['team1'].isin(teams)]
matches=matches[matches['team2'].isin(teams)]

In [15]:
matches.head()

,id,city,team1,team2,winner,target_runs,method
0,335982,Bangalore,Royal Challengers Bengaluru,Kolkata Knight Riders,Kolkata Knight Riders,223.0,NaN
1,335983,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,241.0,NaN
2,335984,Delhi,Delhi Capitals,Rajasthan Royals,Delhi Daredevils,130.0,NaN
3,335985,Mumbai,Mumbai Indians,Royal Challengers Bengaluru,Royal Challengers Bangalore,166.0,NaN
4,335986,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,111.0,NaN

In [16]:
matches=matches.drop(['method'],axis=1)

In [17]:
matches.head()

,id,city,team1,team2,winner,target_runs
0,335982,Bangalore,Royal Challengers Bengaluru,Kolkata Knight Riders,Kolkata Knight Riders,223.0
1,335983,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,241.0
2,335984,Delhi,Delhi Capitals,Rajasthan Royals,Delhi Daredevils,130.0
3,335985,Mumbai,Mumbai Indians,Royal Challengers Bengaluru,Royal Challengers Bangalore,166.0
4,335986,Kolkata,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,111.0

In [18]:
deliveries.head(50)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
11,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
12,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
13,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
14,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
15,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
16,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,P Kumar,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
17,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,P Kumar,SC Ganguly,1,0,1,NaN,0,NaN,NaN,NaN
18,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
19,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,SC Ganguly,0,5,5,wides,0,NaN,NaN,NaN
20,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,BB McCullum,AA Noffke,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
21,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,3,BB McCullum,AA Noffke,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
22,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,4,SC Ganguly,AA Noffke,BB McCullum,4,0,4,NaN,0,NaN,NaN,NaN
23,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,5,SC Ganguly,AA Noffke,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
24,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,6,SC Ganguly,AA Noffke,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
25,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,7,BB McCullum,AA Noffke,SC Ganguly,6,0,6,NaN,0,NaN,NaN,NaN
26,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,1,SC Ganguly,P Kumar,BB McCullum,4,0,4,NaN,0,NaN,NaN,NaN
27,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,2,SC Ganguly,P Kumar,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
28,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,3,BB McCullum,P Kumar,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
29,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
30,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,5,BB McCullum,P Kumar,SC Ganguly,1,0,1,NaN,0,NaN,NaN,NaN
31,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,6,SC Ganguly,P Kumar,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
32,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,1,BB McCullum,Z Khan,SC Ganguly,1,0,1,NaN,0,NaN,NaN,NaN
33,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,2,SC Ganguly,Z Khan,BB McCullum,0,0,0,NaN,1,SC Ganguly,caught,JH Kallis
34,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,3,RT Ponting,Z Khan,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
35,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,4,RT Ponting,Z Khan,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
36,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,5,RT Ponting,Z Khan,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
37,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,6,RT Ponting,Z Khan,BB McCullum,0,0,0,NaN,0,NaN,NaN,NaN
38,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,1,BB McCullum,AA Noffke,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
39,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,2,RT Ponting,AA Noffke,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
40,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,3,BB McCullum,AA Noffke,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
41,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,4,RT Ponting,AA Noffke,BB McCullum,2,0,2,NaN,0,NaN,NaN,NaN
42,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,5,RT Ponting,AA Noffke,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
43,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,6,6,BB McCullum,AA Noffke,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
44,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,1,BB McCullum,Z Khan,RT Ponting,0,0,0,NaN,0,NaN,NaN,NaN
45,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,2,BB McCullum,Z Khan,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
46,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,3,RT Ponting,Z Khan,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
47,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,4,BB McCullum,Z Khan,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
48,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,5,RT Ponting,Z Khan,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
49,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,6,BB McCullum,Z Khan,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN

In [19]:
matches=matches.drop(['team1','team2'],axis=1)

In [20]:
matches.head()

       id        city                       winner  target_runs
0  335982   Bangalore        Kolkata Knight Riders        223.0
1  335983  Chandigarh          Chennai Super Kings        241.0
2  335984       Delhi             Delhi Daredevils        130.0
3  335985      Mumbai  Royal Challengers Bangalore        166.0
4  335986     Kolkata        Kolkata Knight Riders        111.0

In [21]:
matches.rename(columns={'id': 'match_id'}, inplace=True)

In [22]:
matches.head()

   match_id        city                       winner  target_runs
0    335982   Bangalore        Kolkata Knight Riders        223.0
1    335983  Chandigarh          Chennai Super Kings        241.0
2    335984       Delhi             Delhi Daredevils        130.0
3    335985      Mumbai  Royal Challengers Bangalore        166.0
4    335986     Kolkata        Kolkata Knight Riders        111.0

In [23]:
delivery_df=matches.merge(deliveries,on='match_id')

In [24]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [25]:
delivery_df=delivery_df[delivery_df['inning']==2]

In [26]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,AB Dinda,R Dravid,0,1,1,wides,0,NaN,NaN,NaN
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,AB Dinda,R Dravid,0,0,0,NaN,0,NaN,NaN,NaN
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,AB Dinda,R Dravid,1,0,1,NaN,0,NaN,NaN,NaN
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [27]:
delivery_df.shape

(111721, 20)

In [28]:
delivery_df['total_runs'] = pd.to_numeric(delivery_df['total_runs'], errors='coerce')  # Coerce bad values to NaN if needed
delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs'].cumsum()

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\2950266432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['total_runs'] = pd.to_numeric(delivery_df['total_runs'], errors='coerce')  # Coerce bad values to NaN if needed
C:\Users\satha\AppData\Local\Temp\ipykernel_20856\2950266432.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs'].cumsum()

In [29]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,1
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,R Dravid,0,1,1,wides,0,NaN,NaN,NaN,2
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,R Dravid,0,0,0,NaN,0,NaN,NaN,NaN,2
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,R Dravid,1,0,1,NaN,0,NaN,NaN,NaN,3
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,110
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,111
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,112
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,113
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,114

In [30]:
delivery_df['runs_left']=delivery_df['target_runs']-delivery_df['current_score']

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\3387445532.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['runs_left']=delivery_df['target_runs']-delivery_df['current_score']

In [31]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1,0,1,NaN,0,NaN,NaN,NaN,1,222.0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0,1,1,wides,0,NaN,NaN,NaN,2,221.0
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,0,NaN,0,NaN,NaN,NaN,2,221.0
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,1,0,1,NaN,0,NaN,NaN,NaN,3,220.0
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,1,0,1,NaN,0,NaN,NaN,NaN,4,219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,1,0,1,NaN,0,NaN,NaN,NaN,110,4.0
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,1,0,1,NaN,0,NaN,NaN,NaN,111,3.0
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,1,0,1,NaN,0,NaN,NaN,NaN,112,2.0
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,1,0,1,NaN,0,NaN,NaN,NaN,113,1.0
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,1,0,1,NaN,0,NaN,NaN,NaN,114,0.0

In [32]:
delivery_df['balls_left']=120-(delivery_df['over']*6+delivery_df['ball'])

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\3788185712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['balls_left']=120-(delivery_df['over']*6+delivery_df['ball'])

In [33]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,1,NaN,0,NaN,NaN,NaN,1,222.0,119
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,1,wides,0,NaN,NaN,NaN,2,221.0,118
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,NaN,0,NaN,NaN,NaN,2,221.0,117
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,1,NaN,0,NaN,NaN,NaN,3,220.0,116
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,1,NaN,0,NaN,NaN,NaN,4,219.0,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,110,4.0,61
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,111,3.0,60
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,112,2.0,59
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,113,1.0,58
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,114,0.0,57

In [34]:
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1753340267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna("0")
C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1753340267.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")
C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1753340267.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')

In [35]:
delivery_df.head()

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,1,NaN,0,0,NaN,NaN,1,222.0,119
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,1,wides,0,0,NaN,NaN,2,221.0,118
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,NaN,0,0,NaN,NaN,2,221.0,117
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,1,NaN,0,0,NaN,NaN,3,220.0,116
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,1,NaN,0,0,NaN,NaN,4,219.0,115

In [36]:
delivery_df['is_wicket'].dtype

dtype('int64')

In [37]:
delivery_df['is_wicket'] = pd.to_numeric(delivery_df['is_wicket'], errors='coerce')  # Coerce bad values to NaN if needed
delivery_df['is_wicket'] = delivery_df.groupby('match_id')['is_wicket'].cumsum()

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1157391560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['is_wicket'] = pd.to_numeric(delivery_df['is_wicket'], errors='coerce')  # Coerce bad values to NaN if needed
C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1157391560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['is_wicket'] = delivery_df.groupby('match_id')['is_wicket'].cumsum()

In [38]:
delivery_df.head(50)

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,1,NaN,0,0,NaN,NaN,1,222.0,119
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,1,wides,0,0,NaN,NaN,2,221.0,118
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,NaN,0,0,NaN,NaN,2,221.0,117
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,1,NaN,0,0,NaN,NaN,3,220.0,116
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,1,NaN,0,0,NaN,NaN,4,219.0,115
129,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,6,W Jaffer,...,0,0,NaN,0,0,NaN,NaN,4,219.0,114
130,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,7,W Jaffer,...,0,0,NaN,0,0,NaN,NaN,4,219.0,113
131,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,1,R Dravid,...,0,0,NaN,1,1,bowled,NaN,4,219.0,113
132,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,2,V Kohli,...,0,0,NaN,1,0,NaN,NaN,4,219.0,112
133,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,3,V Kohli,...,4,4,legbyes,1,0,NaN,NaN,8,215.0,111
134,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,4,V Kohli,...,0,1,NaN,1,0,NaN,NaN,9,214.0,110
135,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,5,W Jaffer,...,0,0,NaN,1,0,NaN,NaN,9,214.0,109
136,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,6,W Jaffer,...,0,0,NaN,1,0,NaN,NaN,9,214.0,108
137,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,1,V Kohli,...,0,0,NaN,1,0,NaN,NaN,9,214.0,107
138,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,2,V Kohli,...,0,0,NaN,2,1,bowled,NaN,9,214.0,106
139,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,3,JH Kallis,...,0,1,NaN,2,0,NaN,NaN,10,213.0,105
140,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,4,W Jaffer,...,0,0,NaN,2,0,NaN,NaN,10,213.0,104
141,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,5,W Jaffer,...,1,1,wides,2,0,NaN,NaN,11,212.0,103
142,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,6,W Jaffer,...,0,0,NaN,2,0,NaN,NaN,11,212.0,102
143,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,7,W Jaffer,...,0,1,NaN,2,0,NaN,NaN,12,211.0,101
144,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,1,W Jaffer,...,0,2,NaN,2,0,NaN,NaN,14,209.0,101
145,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,2,W Jaffer,...,0,1,NaN,2,0,NaN,NaN,15,208.0,100
146,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,3,JH Kallis,...,0,0,NaN,2,0,NaN,NaN,15,208.0,99
147,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,4,JH Kallis,...,1,1,legbyes,2,0,NaN,NaN,16,207.0,98
148,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,5,W Jaffer,...,0,0,NaN,2,0,NaN,NaN,16,207.0,97
149,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,6,W Jaffer,...,0,0,NaN,2,0,NaN,NaN,16,207.0,96
150,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,1,JH Kallis,...,0,1,NaN,2,0,NaN,NaN,17,206.0,95
151,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,2,W Jaffer,...,0,1,NaN,2,0,NaN,NaN,18,205.0,94
152,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,3,JH Kallis,...,0,0,NaN,2,0,NaN,NaN,18,205.0,93
153,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,4,JH Kallis,...,0,6,NaN,2,0,NaN,NaN,24,199.0,92
154,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,5,JH Kallis,...,0,0,NaN,3,1,caught,M Kartik,24,199.0,91
155,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,6,CL White,...,0,0,NaN,3,0,NaN,NaN,24,199.0,90
156,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,1,W Jaffer,...,0,0,NaN,3,0,NaN,NaN,24,199.0,89
157,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,2,W Jaffer,...,0,0,NaN,4,1,caught,RT Ponting,24,199.0,88
158,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,3,MV Boucher,...,0,0,NaN,4,0,NaN,NaN,24,199.0,87
159,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,4,MV Boucher,...,0,1,NaN,4,0,NaN,NaN,25,198.0,86
160,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,5,CL White,...,0,1,NaN,4,0,NaN,NaN,26,197.0,85
161,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,6,MV Boucher,...,0,0,NaN,4,0,NaN,NaN,26,197.0,84
162,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,1,CL White,...,0,0,NaN,4,0,NaN,NaN,26,197.0,83
163,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,2,CL White,...,0,0,NaN,4,0,NaN,NaN,26,197.0,82
164,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,3,CL White,...,0,1,NaN,4,0,NaN,NaN,27,196.0,81
165,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,4,MV Boucher,...,1,1,wides,4,0,NaN,NaN,28,195.0,80
166,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,5,MV Boucher,...,1,1,wides,4,0,NaN,NaN,29,194.0,79
167,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,6,MV Boucher,...,0,0,NaN,4,0,NaN,NaN,29,194.0,78
168,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,7,MV Boucher,...,0,0,NaN,4,0,NaN,NaN,29,194.0,77
169,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,8,MV Boucher,...,0,4,NaN,4,0,NaN,NaN,33,190.0,76
170,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,1,CL White,...,0,1,NaN,4,0,NaN,NaN,34,189.0,77
171,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,2,MV Boucher,...,1,1,legbyes,4,0,NaN,NaN,35,188.0,76
172,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,3,CL White,...,0,1,NaN,4,0,NaN,NaN,36,187.0,75
173,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,4,MV Boucher,...,0,2,NaN,4,0,NaN,NaN,38,185.0,74

In [39]:
delivery_df['wickets_left']=10-delivery_df['is_wicket']

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\2203161881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['wickets_left']=10-delivery_df['is_wicket']

In [40]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1,NaN,0,0,NaN,NaN,1,222.0,119,10
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,wides,0,0,NaN,NaN,2,221.0,118,10
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,NaN,0,0,NaN,NaN,2,221.0,117,10
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,1,NaN,0,0,NaN,NaN,3,220.0,116,10
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,1,NaN,0,0,NaN,NaN,4,219.0,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,1,NaN,2,0,NaN,NaN,110,4.0,61,8
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,1,NaN,2,0,NaN,NaN,111,3.0,60,8
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,1,NaN,2,0,NaN,NaN,112,2.0,59,8
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,1,NaN,2,0,NaN,NaN,113,1.0,58,8
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,1,NaN,2,0,NaN,NaN,114,0.0,57,8

In [41]:
delivery_df['crr']=(delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\1289864394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['crr']=(delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

In [42]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left,crr
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,NaN,0,0,NaN,NaN,1,222.0,119,10,6.000000
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,wides,0,0,NaN,NaN,2,221.0,118,10,6.000000
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,NaN,0,0,NaN,NaN,2,221.0,117,10,4.000000
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,NaN,0,0,NaN,NaN,3,220.0,116,10,4.500000
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,NaN,0,0,NaN,NaN,4,219.0,115,10,4.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,NaN,2,0,NaN,NaN,110,4.0,61,8,11.186441
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,NaN,2,0,NaN,NaN,111,3.0,60,8,11.100000
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,NaN,2,0,NaN,NaN,112,2.0,59,8,11.016393
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,NaN,2,0,NaN,NaN,113,1.0,58,8,10.935484
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,NaN,2,0,NaN,NaN,114,0.0,57,8,10.857143

In [43]:
delivery_df['rrr']=(delivery_df['runs_left']*6)/(delivery_df['balls_left'])

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\297266893.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['rrr']=(delivery_df['runs_left']*6)/(delivery_df['balls_left'])

In [44]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left,crr,rrr
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,0,NaN,NaN,1,222.0,119,10,6.000000,11.193277
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0,0,NaN,NaN,2,221.0,118,10,6.000000,11.237288
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,NaN,NaN,2,221.0,117,10,4.000000,11.333333
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,0,NaN,NaN,3,220.0,116,10,4.500000,11.379310
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,0,NaN,NaN,4,219.0,115,10,4.800000,11.426087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,2,0,NaN,NaN,110,4.0,61,8,11.186441,0.393443
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,2,0,NaN,NaN,111,3.0,60,8,11.100000,0.300000
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,2,0,NaN,NaN,112,2.0,59,8,11.016393,0.203390
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,2,0,NaN,NaN,113,1.0,58,8,10.935484,0.103448
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,2,0,NaN,NaN,114,0.0,57,8,10.857143,0.000000

In [45]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [46]:
delivery_df['result']=delivery_df.apply(result,axis=1)

C:\Users\satha\AppData\Local\Temp\ipykernel_20856\2671046774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delivery_df['result']=delivery_df.apply(result,axis=1)

In [47]:
delivery_df

,match_id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left,crr,rrr,result
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,NaN,NaN,1,222.0,119,10,6.000000,11.193277,0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0,NaN,NaN,2,221.0,118,10,6.000000,11.237288,0
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,NaN,NaN,2,221.0,117,10,4.000000,11.333333,0
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,0,NaN,NaN,3,220.0,116,10,4.500000,11.379310,0
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,0,NaN,NaN,4,219.0,115,10,4.800000,11.426087,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230977,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,0,NaN,NaN,110,4.0,61,8,11.186441,0.393443,1
230978,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,0,NaN,NaN,111,3.0,60,8,11.100000,0.300000,1
230979,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,0,NaN,NaN,112,2.0,59,8,11.016393,0.203390,1
230980,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,0,NaN,NaN,113,1.0,58,8,10.935484,0.103448,1
230981,1426312,Chennai,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,0,NaN,NaN,114,0.0,57,8,10.857143,0.000000,1

In [48]:
delivery_df=delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets_left','target_runs','crr','rrr','result']]

In [49]:
delivery_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target_runs,crr,rrr,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,222.0,119,10,223.0,6.000000,11.193277,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221.0,118,10,223.0,6.000000,11.237288,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221.0,117,10,223.0,4.000000,11.333333,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,220.0,116,10,223.0,4.500000,11.379310,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,219.0,115,10,223.0,4.800000,11.426087,0
...,...,...,...,...,...,...,...,...,...,...
230977,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,4.0,61,8,114.0,11.186441,0.393443,1
230978,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,3.0,60,8,114.0,11.100000,0.300000,1
230979,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,2.0,59,8,114.0,11.016393,0.203390,1
230980,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,1.0,58,8,114.0,10.935484,0.103448,1
230981,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,0.0,57,8,114.0,10.857143,0.000000,1

In [50]:
final_df=delivery_df

In [51]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target_runs,crr,rrr,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,222.0,119,10,223.0,6.000000,11.193277,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221.0,118,10,223.0,6.000000,11.237288,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,221.0,117,10,223.0,4.000000,11.333333,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,220.0,116,10,223.0,4.500000,11.379310,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,219.0,115,10,223.0,4.800000,11.426087,0
...,...,...,...,...,...,...,...,...,...,...
230977,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,4.0,61,8,114.0,11.186441,0.393443,1
230978,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,3.0,60,8,114.0,11.100000,0.300000,1
230979,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,2.0,59,8,114.0,11.016393,0.203390,1
230980,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,1.0,58,8,114.0,10.935484,0.103448,1
230981,Kolkata Knight Riders,Sunrisers Hyderabad,Chennai,0.0,57,8,114.0,10.857143,0.000000,1

In [52]:
final_df=final_df.sample(final_df.shape[0])

In [53]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target_runs,crr,rrr,result
224101,Punjab Kings,Kolkata Knight Riders,Kolkata,65.0,35,8,262.0,13.905882,11.142857,1

In [54]:
final_df.dropna(inplace=True)

In [55]:
final_df=final_df[final_df['balls_left']!=0]

In [56]:
X=final_df.drop(['result'],axis=1)
y=final_df['result']

In [57]:
X.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target_runs,crr,rrr
123090,Royal Challengers Bangalore,Kings XI Punjab,Bengaluru,109.0,79,8,156.0,6.878049,8.278481
131109,Rajasthan Royals,Chennai Super Kings,Jaipur,118.0,81,8,177.0,9.076923,8.740741
122585,Chennai Super Kings,Kolkata Knight Riders,Chennai,150.0,97,10,203.0,13.826087,9.278351
197193,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,77.0,1,2,204.0,6.403361,462.000000
99934,Kolkata Knight Riders,Chennai Super Kings,Chennai,66.0,61,7,135.0,7.016949,6.491803

In [58]:
y.head()

123090    1
131109    1
122585    1
197193    0
99934     0
Name: result, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf = ColumnTransformer([
    ('trf',OneHotEncoder(drop='first'),['batting_team','bowling_team','city'])
],remainder='passthrough')

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [62]:
pipe=Pipeline([
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [63]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first'),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [64]:
y_pred=pipe.predict(X_test)

In [65]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8069675827044472

In [66]:
import pickle

In [67]:
pickle.dump(pipe,open('pipe.pkl','wb'))

In [68]:
final_df

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,target_runs,crr,rrr,result
123090,Royal Challengers Bangalore,Kings XI Punjab,Bengaluru,109.0,79,8,156.0,6.878049,8.278481,1
131109,Rajasthan Royals,Chennai Super Kings,Jaipur,118.0,81,8,177.0,9.076923,8.740741,1
122585,Chennai Super Kings,Kolkata Knight Riders,Chennai,150.0,97,10,203.0,13.826087,9.278351,1
197193,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,77.0,1,2,204.0,6.403361,462.000000,0
99934,Kolkata Knight Riders,Chennai Super Kings,Chennai,66.0,61,7,135.0,7.016949,6.491803,0
...,...,...,...,...,...,...,...,...,...,...
36185,Kings XI Punjab,Mumbai Indians,Chandigarh,94.0,76,9,155.0,8.318182,7.421053,1
74821,Rajasthan Royals,Delhi Daredevils,Jaipur,4.0,17,9,155.0,8.796117,1.411765,1
215268,Royal Challengers Bengaluru,Punjab Kings,Bengaluru,145.0,99,9,177.0,9.142857,8.787879,1
98344,Royal Challengers Bangalore,Chennai Super Kings,Bangalore,32.0,2,3,182.0,7.627119,96.000000,0
171989,Delhi Capitals,Sunrisers Hyderabad,Dubai,115.0,105,10,135.0,8.000000,6.571429,1

In [69]:
final_df['city'].unique()

array(['Bengaluru', 'Jaipur', 'Chennai', 'Hyderabad', 'Mumbai',
       'Navi Mumbai', 'Sharjah', 'Port Elizabeth', 'Kolkata',
       'Chandigarh', 'Bangalore', 'Pune', 'Dharamsala', 'Cuttack',
       'Delhi', 'Nagpur', 'Visakhapatnam', 'Abu Dhabi', 'Dubai', 'Durban',
       'Mohali', 'Ahmedabad', 'Raipur', 'Centurion', 'Ranchi', 'Lucknow',
       'Indore', 'Johannesburg', 'Cape Town', 'Guwahati', 'East London',
       'Bloemfontein', 'Kimberley'], dtype=object)

In [70]:
pipe

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first'),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [74]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [72]:
import joblib
joblib.dump(pipe,'pipe.pkl')

['pipe.pkl']

In [73]:
import sklearn
print(sklearn.__version__)

1.7.0